services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      DB_NAME: esgbuddy
      DB_USER: postgres
      DB_PASSWORD: ${POSTGRES_PASS}
      DB_HOST: host.docker.internal

    container_name: fastapi


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "800:80"
    container_name: nginx_front
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=/api
    