"""add pdf fields to message

Revision ID: ddf0f00e0144
Revises: 579821be7a96
Create Date: 2025-12-13 11:54:11.573666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddf0f00e0144'
down_revision: Union[str, None] = '579821be7a96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('has_pdf', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('pdf_filename', sa.String(length=255), nullable=True))
    op.add_column('messages', sa.Column('pdf_data', sa.LargeBinary(), nullable=True))
    op.add_column('messages', sa.Column('pdf_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'pdf_size')
    op.drop_column('messages', 'pdf_data')
    op.drop_column('messages', 'pdf_filename')
    op.drop_column('messages', 'has_pdf')
    # ### end Alembic commands ###
